<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <UseWPF>true</UseWPF>
    <AssemblyName>AuraFlow</AssemblyName>
    <RootNamespace>AuraFlow.App</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
    <DebugType>none</DebugType>
    <DebugType Condition="'$(Configuration)'=='Debug'">portable</DebugType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Hardcodet.NotifyIcon.Wpf" Version="2.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AuraFlow.OpenRgb\AuraFlow.OpenRgb.csproj" />
  </ItemGroup>

</Project>
